//the try statement allows u to define a block of code to b tested for errors while it is being executed
//the catchstatement allows u to define a block of code to b executed,if an error occors n the try block
console.log("snobbar ")
console.log("snobbar ")
try{
    console.log(s)
}
catch(err){
    
    console.log("caught an error..s is not defined")
    console.log(err)
}

console.log("snobbar ")
console.log("snobbar ")